# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Foocus
description:      ""

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://foocus.fr" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/edi9999/foocus.fr
